persistence:
  defaultClass: true
  defaultClassReplicaCount: 1

defaultSettings:
  defaultReplicaCount: 1
  replicaAutoBalance: disabled 

networkPolicies:
  enabled: false

privateRegistry:
  registryUrl: ""
  user: ""
  password: ""

global:
  cattle:
    systemDefaultRegistry: ""
