apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd 
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 77.6.2           
    helm:
      valueFiles:
        - $values/platform/monitoring/values-rpi.yaml
  - repoURL: https://github.com/Mekaze99/k3s-home-lab.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/Mekaze99/k3s-home-lab.git
    targetRevision: main
    path: platform/monitoring
    directory:
      recurse: false
      exclude: values-*.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
